### PR TITLE
Allow Disabling of the Automatic Display of User Messages

### PR DESCRIPTION
**Pull request by DrGodCarl**
I've created a prop which prevents the default behavior of updating the view with the new user message. Consumers of this widget can disable auto-adding in order to either customize the user's input in some way before sending it back using `addUserMessage`, or to rig it up so that text is only displayed once it has reached the server. 

I've set all defaults to the previous behavior so this is non-breaking for people upgrading to it.
I believe this will solve Issue #45, or at least provide the tools for it to be solved easily.

Full disclosure, I'm new to Jest so if I have taken any missteps in my testing, please let me know and direct me to proper resources and I'll do my best to fix them; similarly, if someone out there wants to tune them up I'm more than happy to accept the help. There wasn't any validation around redux behavior so I just piggy-backed onto the mocked dispatch function, validating its input as that seemed better than nothing.

### CODE REVIEW

**Comment by Edison4mobile** [comment]
autoAddUserMessage
I installed using npm install but I am not able to use above props.
It seems it is not merged to master.
Could you please merge this mater so that i can use? thanks so much.

**Comment by petarzoric** [comment]
How to install it? Tried different approaches that I found online and it's not working for me...

**Comment by DrGodCarl** [comment]
They haven't merged this yet but if you want to use it for now you can do so by adding it to your package.json like:
`"react-chat-widget": "github:DrGodCarl/react-chat-widget#allow-custom-user-message-handling-build",`
Generally not recommended, especially for you, because I could change it out from under you or delete that branch, but if you want to use my code that's how to do it.

**Comment by PushkarDureja** [comment]
Now is it merged to master branch?? I want to use it can you guide me how to do include it?

**Pull request closed without merging**
