### PR TITLE
Scope header css class to conversation-container

### PR DESCRIPTION
**Pull request by charlesj**
This was causing the problem I described in #20.  A simple scss class scope fixed the problem.  I realize that there might be other places where similar changes might need to be made, but I thought I should keep it to the smallest change possible for this particular fix.  I'm open to taking on the more extensive change, but would also need to become much more familiar with your code before I can take that on.

### CODE REVIEW

**Comment by mcallegari10** [comment]
@charlesj  I really want to stay fully customizable, are you sure this change won't make more difficult to accomplish that?

**Comment by charlesj** [comment]
I'm not sure I see the connection to customizability. All this PR does is change the css output so that header styles defined in this component do not leak outside of the component.  Am I missing something?

**Comment by mcallegari10** [comment]
That's correct, but the way you can customize this widget is by overriding the classes, I just want to confirm the nesting you added won't interfere with that.

**Comment by charlesj** [comment]
It doesn't.  Let's consider the two cases:

1) Existing customizations targeting `.header` by itself. These continue to work against the component because the name of the class is the same.

2) Future customizations:  They can either target `.header` directly, or they can override using the more targeted: `.conversation-container .header`.

We have a private fork of the component pending this PR where we have done exactly that.

**Comment by Thomas-Negrault** [comment]
How can I use this feature ?
When I run
`npm install --save react-chat-widget`
I have the version without the fix (every div in my app with the class `.title` have` font-size: 24px;` )
I found the command to install a library from github:
` npm install git://github.com/Wolox/react-chat-widget.git#master --save`
But when I run this command, the /node_modules/react-chat-widget directory only contain:

- CONTRIBUTING.MD
- LICENSE
- package.json
- README.md

How do I add this library with your fix to my app ?

**Comment by adantoscano** [comment]
You have to clone the repo, build it and then link compile stuff with your new project.

npm pacackage is in older version than github, I guess

**Comment by khushal87** [comment]
Is it fixed?
I am still facing the same issue can anyone help me out?

**Pull request merged**
